services:
  microservicios-postgres14:
    container_name: microservicios-postgres14
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_springboot_cloud
      POSTGRES_PASSWORD: root
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - springcloud

  servicio-usuarios:
    container_name: servicio-usuarios
    build:
      context: ./springboot-servicio-usuarios/
      dockerfile: Dockerfile
    image: servicio-usuarios:v1
    environment:
        DB_HOST: microservicios-postgres14:5432
        DB_DATABASE: db_springboot_cloud
        DB_USERNAME: postgres
        DB_PASSWORD: root
        CONFIG_SERVER_URL: ec2-54-237-47-39.compute-1.amazonaws.com:8888
        EUREKA_SERVER_URL: ec2-54-237-47-39.compute-1.amazonaws.com:8761
    networks:
      - springcloud
    depends_on:
      #- config-server
      #- servicio-eureka-server
      - microservicios-postgres14
    restart: unless-stopped

volumes:
  data-postgres:

networks:
  springcloud: